import 'tool_param.dart';

/// Definition of an MCP tool — name, description, parameters, integration.
///
/// Each registered tool produces the JSON object the MCP protocol returns
/// from `tools/list`, matching the shape generated by the Java
/// `MCPSchemaGenerator`.
class ToolDefinition {
  /// Snake-case tool name, e.g. `"jira_post_comment"`.
  final String name;

  /// Human-readable summary shown to the MCP client.
  final String description;

  /// Owning integration, e.g. `"jira"`, `"github"`.
  final String integration;

  /// Optional grouping, e.g. `"issues"`, `"comments"`.
  final String category;

  /// Cross-integration aliases, e.g. `["tracker_post_comment"]`.
  final List<String> aliases;

  /// Ordered list of accepted parameters.
  final List<ToolParam> params;

  /// Creates a tool definition.
  const ToolDefinition({
    required this.name,
    required this.description,
    required this.integration,
    this.category = '',
    this.aliases = const [],
    this.params = const [],
  });

  /// Returns the required parameter names, in declaration order.
  List<String> get requiredParams =>
      params.where((p) => p.required).map((p) => p.name).toList();

  /// Returns [args] with Java parameter aliases normalized onto the
  /// canonical parameter names (`MCPSchemaGenerator` executor parity:
  /// "check parameter X and its aliases"). Alias keys are preserved —
  /// handlers read canonical keys only.
  Map<String, dynamic> applyParamAliases(Map<String, dynamic> args) {
    var out = args;
    for (final p in params) {
      if (p.aliases.isEmpty || out.containsKey(p.name)) continue;
      for (final alias in p.aliases) {
        if (out.containsKey(alias)) {
          out = {...out, p.name: out[alias]};
          break;
        }
      }
    }
    return out;
  }

  /// Converts to MCP protocol JSON.
  ///
  /// Matches the Java `MCPSchemaGenerator` output: a tool object with
  /// `name`, `integration`, `category`, `description`, and an
  /// `inputSchema` JSON Schema.
  Map<String, dynamic> toJson() {
    final properties = <String, Map<String, dynamic>>{};
    for (final p in params) {
      properties[p.name] = p.toJson();
    }
    return {
      'name': name,
      'integration': integration,
      'category': category,
      'description': description,
      'inputSchema': {
        'type': 'object',
        'properties': properties,
        'required': requiredParams,
      },
    };
  }
}
